### ISSUE TITLE
Water_Level is missing

### ISSUE THREAD

**Issue by thexclu** [randomcoffeesnob/decent-advanced-rest-api#7]
here is my configurations.yaml
```
rest:
    - resource: http://192.168.2.101:8888/api/status/details
      scan_interval: 2
      sensor:
      - name: Decent Espresso State
        unique_id: decentespresso_state
        value_template: "{{ value_json.state }}"
      - name: Decent Espresso Substate
        unique_id: decentespresso_substate
        value_template: "{{ value_json.substate }}"
      - name: Decent Espresso Shot Count
        unique_id: decentespresso_espresso_count
        value_template: "{{ value_json.espresso_count|is_defined }}"
      - name: Decent Espresso Steam Count
        unique_id: decentespresso_steaming_count
        value_template: "{{ value_json.steaming_count|is_defined }}"
      - name: Decent Espresso Head Temperature
        unique_id: decentespresso_head_temp
        value_template: "{{ value_json.head_temperature|default(0)|round(1) }}"
        unit_of_measurement: "  C"
      - name: Decent Espresso Mix Temperature
        unique_id: decentespresso_mix_temp
        value_template: "{{ value_json.mix_temperature|default(0)|round(1) }}"
        unit_of_measurement: "  C"
      - name: Decent Espresso Steam Temperature
        unique_id: decentespresso_steam_temp
        value_template: "{{ value_json.steam_heater_temperature|default(0)|round(1) }}"
        unit_of_measurement: "  C"
      - name: Decent Espresso Water Level
        unique_id: decentespresso_water_level
        value_template: "{{ value_json.water_level|replace(' mL', '')|default(0) }}"
        unit_of_measurement: ml
      - name: Decent Espresso Profile
        unique_id: decentespresso_profile
        value_template: "{{ value_json.profile|replace('_', ' ') }}"

switch:
    - platform: rest
      name: "Decent Espresso"
      resource: http://192.168.2.101:8888/api/status
      body_on: '{"active": "true"}'
      body_off: '{"active": "false"}'
      is_on_template: "{{ value_json.is_active }}"
      headers:
          Content-Type: application/json
```

In my home assistant:
![image](https://github.com/randomcoffeesnob/decent-advanced-rest-api/assets/26009982/f4d4d7bb-194c-40d6-89c0-b4df4564ff7e)

Pure http request:

![CleanShot 2023-08-06 at 22 28 59](https://github.com/randomcoffeesnob/decent-advanced-rest-api/assets/26009982/5f902388-5326-402d-9d03-16fa5dd48dee)

you can see when i GET from /api/details . water_level is missing in response
